### ISSUE TITLE
rust-toolchain configuration now out of date

### ISSUE THREAD

**Issue by stephanhorsthemke** [fastly/fastly-template-rust-default#10]
After yesterday's update the rust toolchain is at 1.43.0, however the `rust-toolchain` config file still configures is to 1.40.0.
I had to update it manually in my existing packages, but also the initialization of new projects does not work.

Reproduction should be possible just with.
$ fastly compute init
$ fastly compute build
$ fastly compute deploy

I get an "Internal Server Error" when I GET the services URL.

changing `rust-toolchain` to 1.43.0 should fix it.

**Comment by phamann** [comment]
Thank you for the report @stephanhorsthemke. We had a discussion internally whether to update this file or remove it completely and seems we dropped the ball on a decision. I am going to update the toolchain file now to ensure any new projects pull down the correct version, and follow up with the team to make a final decision on whether we should keep the file.

I am however intrigued as to how this is causing your projects to fail, as we explicitly force a toolchain via `cargo build +toolchain` during `fastly compute build` (CLI code for this can be found [here](https://github.com/fastly/cli/blob/master/pkg/compute/rust.go#L164-L178)) which should be taking precedence over any toolchain file that exists in the project, as per the override of precedence rule defined [here](https://github.com/rust-lang/rustup#override-precedence).

Are you able to do some further testing to confirm that the `rust-toolchain` is having any impact on your `fastly compute build`. Such as chaging to file back to 1.40.0 and running `fastly compute build` with the `-v` verbose flag to see if it has to recompile targets.

**Comment by stephanhorsthemke** [comment]
You seem to be right, I tried to reproduce and failed. Also I saw at least the checking for `1.43.0` with verbose output.
Thanks for the clarification!
